name: CI

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install core deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Static checks (optional)
        run: |
          python -m compileall src || exit 1

      - name: Build Docker (CLI)
        run: docker build -f docker/Dockerfile.cli -t ghcr.io/${{ github.repository }}/mini-stock-cli:${{ github.sha }} .

      - name: Build Docker (Gradio)
        run: docker build -f docker/Dockerfile.gradio -t ghcr.io/${{ github.repository }}/mini-stock-gradio:${{ github.sha }} .
